# Generated by Django 3.2.3 on 2021-05-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['title', 'slug'], name='images_imag_title_8fa1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['slug'], name='slug_idx'),
        ),
    ]
